# Generated by Django 4.0.1 on 2024-04-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('administrative_district', models.CharField(max_length=15)),
                ('city_planning_area', models.CharField(max_length=15)),
                ('structure', models.CharField(max_length=5)),
                ('area', models.FloatField()),
                ('orientation', models.CharField(max_length=20)),
                ('decoration', models.CharField(max_length=2)),
                ('house_type', models.CharField(max_length=4)),
                ('floor_height', models.CharField(max_length=3)),
                ('floor_count', models.IntegerField()),
                ('price', models.FloatField()),
                ('latitude_bd', models.FloatField()),
                ('longitude_bd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='POIInfo',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('administrative_district', models.CharField(max_length=15)),
                ('first_tag', models.CharField(max_length=10)),
                ('second_tag', models.CharField(max_length=10)),
                ('latitude_bd', models.FloatField()),
                ('longitude_bd', models.FloatField()),
            ],
        ),
    ]
